import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  String _currentLanguage = 'en'; // 'en' for English, 'fr' for French

  String get currentLanguage => _currentLanguage;

  void setLanguage(String language) {
    _currentLanguage = language;
    notifyListeners();
  }

  String getText(String key) {
    if (_currentLanguage == 'fr') {
      return _frenchTexts[key] ?? key;
    }
    return _englishTexts[key] ?? key;
  }

  static const Map<String, String> _englishTexts = {
    'login': 'LOGIN',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'otp': 'OTP Code',
    'send_otp': 'Send OTP',
    'verify_otp': 'VERIFY OTP',
    'biometric_login': 'BIOMETRIC LOGIN',
    'create_account': 'Create Account',
    'welcome_back': 'Welcome back',
    'wallet_balance': 'Wallet Balance',
    'send': 'Send',
    'receive': 'Receive',
    'recent_transactions': 'Recent Transactions',
    'no_transactions': 'No transactions yet',
    'received': 'Received',
    'sent': 'Sent',
    'home': 'Home',
    'profile': 'Profile',
    'settings': 'Settings',
    'logout': 'Logout',
    'language': 'Language',
    'english': 'English',
    'french': 'Français',
    'notifications': 'Notifications',
    'security': 'Security',
    'about': 'About',
    'biometric_settings': 'Biometric Settings',
    'change_passphrase': 'Change Passphrase',
    'enable_biometric': 'Enable Biometric',
    'face_id': 'Face ID',
    'fingerprint': 'Fingerprint',
    'save': 'Save',
    'cancel': 'Cancel',
    'old_passphrase': 'Old Passphrase',
    'new_passphrase': 'New Passphrase',
    'confirm_passphrase': 'Confirm Passphrase',
    'passphrase_mismatch': 'Passphrases do not match',
    'passphrase_changed': 'Passphrase changed successfully',
    'error': 'Error',
    'success': 'Success',
    'login_failed': 'Login failed',
    'registration_failed': 'Registration failed',
    'otp_sent': 'OTP sent to email',
    'otp_verification_failed': 'OTP verification failed',
    'biometric_login_failed': 'Biometric login failed',
    'enter_email_first': 'Enter email first',
    'authenticate_to_access': 'Authenticate to access your wallet',
    'public_key': 'Public Key',
    'amount': 'Amount',
    'to_address': 'To Address',
    'send_transaction': 'Send Transaction',
    'receive_address': 'Receive Address',
    'copy': 'Copy',
    'copied': 'Copied to clipboard',
    'scan_qr': 'Scan QR Code',
    'invalid_address': 'Invalid address',
    'insufficient_balance': 'Insufficient balance',
    'transaction_sent': 'Transaction sent successfully',
    'transaction_failed': 'Transaction failed',
    'loading': 'Loading...',
    'retry': 'Retry',
    'ok': 'OK',
  };

  static const Map<String, String> _frenchTexts = {
    'login': 'CONNEXION',
    'register': 'S\'inscrire',
    'email': 'Email',
    'password': 'Mot de passe',
    'otp': 'Code OTP',
    'send_otp': 'Envoyer OTP',
    'verify_otp': 'VÉRIFIER OTP',
    'biometric_login': 'CONNEXION BIOMÉTRIQUE',
    'create_account': 'Créer un compte',
    'welcome_back': 'Bienvenue',
    'wallet_balance': 'Solde du portefeuille',
    'send': 'Envoyer',
    'receive': 'Recevoir',
    'recent_transactions': 'Transactions récentes',
    'no_transactions': 'Aucune transaction pour le moment',
    'received': 'Reçu',
    'sent': 'Envoyé',
    'home': 'Accueil',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'logout': 'Déconnexion',
    'language': 'Langue',
    'english': 'English',
    'french': 'Français',
    'notifications': 'Notifications',
    'security': 'Sécurité',
    'about': 'À propos',
    'biometric_settings': 'Paramètres biométriques',
    'change_passphrase': 'Changer la phrase secrète',
    'enable_biometric': 'Activer biométrique',
    'face_id': 'Face ID',
    'fingerprint': 'Empreinte digitale',
    'save': 'Sauvegarder',
    'cancel': 'Annuler',
    'old_passphrase': 'Ancienne phrase secrète',
    'new_passphrase': 'Nouvelle phrase secrète',
    'confirm_passphrase': 'Confirmer la phrase secrète',
    'passphrase_mismatch': 'Les phrases secrètes ne correspondent pas',
    'passphrase_changed': 'Phrase secrète changée avec succès',
    'error': 'Erreur',
    'success': 'Succès',
    'login_failed': 'Échec de la connexion',
    'registration_failed': 'Échec de l\'inscription',
    'otp_sent': 'OTP envoyé à l\'email',
    'otp_verification_failed': 'Échec de la vérification OTP',
    'biometric_login_failed': 'Échec de la connexion biométrique',
    'enter_email_first': 'Entrez d\'abord l\'email',
    'authenticate_to_access': 'Authentifiez-vous pour accéder à votre portefeuille',
    'public_key': 'Clé publique',
    'amount': 'Montant',
    'to_address': 'Adresse de destination',
    'send_transaction': 'Envoyer la transaction',
    'receive_address': 'Adresse de réception',
    'copy': 'Copier',
    'copied': 'Copié dans le presse-papiers',
    'scan_qr': 'Scanner le code QR',
    'invalid_address': 'Adresse invalide',
    'insufficient_balance': 'Solde insuffisant',
    'transaction_sent': 'Transaction envoyée avec succès',
    'transaction_failed': 'Échec de la transaction',
    'loading': 'Chargement...',
    'retry': 'Réessayer',
    'ok': 'OK',
  };
}